version: '3'

includes:
  infra:
    taskfile: infra/Taskfile.yml
    dir: infra

  config:
    taskfile: infra/config/Taskfile.yml
    dir: infra/config

  web-app:
    taskfile: web-app/Taskfile.yml
    dir: web-app

  web-app:infra:foundation:
    taskfile: web-app/infra/foundation/Taskfile.yml
    dir: web-app/infra/foundation

  web-app:infra:domain-mapping:
    taskfile: web-app/infra/domain-mapping/Taskfile.yml
    dir: web-app/infra/domain-mapping

  api:impl:
    taskfile: backend/api/Taskfile.yml
    dir: backend/api

  api:infra:foundation:
    taskfile: backend/infra/foundation/Taskfile.yml
    dir: backend/infra/foundation

  api:infra:domain-mapping:
    taskfile: backend/infra/domain-mapping/Taskfile.yml
    dir: backend/infra/domain-mapping

  cli:
    taskfile: cli/Taskfile.yml
    dir: cli

tasks:
  github:lint:
    desc: Lint GitHub workflows
    sources:
      - '.github/workflows/*.yml'
    cmds:
      - github-ci lint

  github:lint:fix:
    desc: Fix lint issues in GitHub workflows
    sources:
      - '.github/workflows/*.yml'
    cmds:
      - github-ci lint --fix

  github:upgrade:
    desc: Upgrade GitHub workflow actions to the latest versions
    cmds:
      - github-ci upgrade

  all:fmt:check:
    desc: Check formatting for the entire codebase
    deps:
      - github:lint
      - infra:fmt:check
      - config:fmt:check
      - web-app:fmt:check
      - web-app:infra:foundation:fmt:check
      - web-app:infra:domain-mapping:fmt:check
      - api:impl:fmt:check
      - api:infra:foundation:fmt:check
      - api:infra:domain-mapping:fmt:check
      - cli:fmt:check

  all:fmt:fix:
    desc: Fix formatting for the entire codebase
    deps:
      - github:lint:fix
      - infra:fmt:fix
      - config:fmt:fix
      - web-app:fmt:fix
      - web-app:infra:foundation:fmt:fix
      - web-app:infra:domain-mapping:fmt:fix
      - api:impl:fmt:fix
      - api:infra:foundation:fmt:fix
      - api:infra:domain-mapping:fmt:fix
      - cli:fmt:fix

  all:lint:
    desc: Lint the entire codebase
    deps:
      - github:lint
      - infra:lint
      - config:lint
      - web-app:lint
      - web-app:infra:foundation:lint
      - web-app:infra:domain-mapping:lint
      - api:impl:lint
      - api:infra:foundation:lint
      - api:infra:domain-mapping:lint
      - cli:lint

  all:analyze:
    desc: Analyze the entire codebase
    deps:
      - infra:validate
      - config:validate
      - config:check
      - web-app:analyze
      - web-app:infra:foundation:validate
      - web-app:infra:domain-mapping:validate
      - api:infra:foundation:validate
      - api:infra:domain-mapping:validate
      - cli:build
      - cli:test

  run:
    desc: Run the frontend and the API locally
    deps:
      - web-app:run
      - api:impl:run
