name: Check Web app implementation

on:
  workflow_call:

permissions:
  contents: read

env:
  NODE_VERSION: 24
  NO_COLOR: 1

  FRONTEND_PATH: web-app/frontend

jobs:
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-node@v6.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          cache-dependency-path: ${{ env.FRONTEND_PATH }}/yarn.lock

      - uses: bufbuild/buf-action@v1.4.0
        with:
          setup_only: true

      - uses: go-task/setup-task@v2

      - name: Check formatting and lint
        run: task fmt:check lint
        working-directory: ${{ env.FRONTEND_PATH }}

      - name: Test
        run: task test
        working-directory: ${{ env.FRONTEND_PATH }}

      - name: Build frontend
        run: task build
        working-directory: ${{ env.FRONTEND_PATH }}
